apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: npm
    image: amazon/aws-sam-cli-build-image-provided
    command:
    - sh
    - -c
    - |
      apk update
      apk add nodejs npm
      node -v
      npm -v
    tty: true
